### ISSUE TITLE
[Bug]: 图片发送超时

### ISSUE THREAD

**Issue by BiFangKNT** [RockChinQ/LangBot#917]
### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 运行环境

docker

### QChatGPT版本

v3.3.1.1

### 异常情况

对于同一张图片，在不同的账号或群里，bot的发送状况不一样，在一些账号（目前仅测出我的主账号可以）中可以正常发送图片，而在其他账号或群中发送不了，控制台中会返回以下信息：
```
[2024-11-09 15:09:50.515] /app/pkg/pipeline/controller.py (167) - [ERROR] :
    处理请求时出错 query_id=5 stage=SendResponseBackStage : <ActionFailed status='failed', retcode=1200, data=None, message='Error: Timeout: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 0,\n    "errMsg": ""\n}\n\n    at Timeout.sendDataCallback [as _onTimeout] (file:///app/napcat/napcat.mjs:7886:15)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', wording='Error: Timeout: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 0,\n    "errMsg": ""\n}\n\n    at Timeout.sendDataCallback [as _onTimeout] (file:///app/napcat/napcat.mjs:7886:15)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', echo={'seq': 1}>
```

与管理员权限无关，我试过给我朋友权限，依旧发送失败。与网络环境也无关，我试过我的主账号在流量环境下依旧可以接收图片

图片并不是敏感图片，应该也与风控无关。

图片如下：
https://github.com/user-attachments/assets/8a5953b1-196a-4775-b7ef-0e8351718254

目前仅测出此图片出问题，其他普通图片都能正常发送

### 启用的插件

使用的插件：
https://github.com/BiFangKNT/QChatGPT_AntiHotlinkImageFetcher

**Comment by RockChinQ** [comment]
这个估计就是图片太大了吧，应该是消息平台的问题，我们没法解决。

**Comment by BiFangKNT** [comment]
> 这个估计就是图片太大了吧，应该是消息平台的问题，我们没法解决。

那为什么我的主账号可以正常发送呢

**Comment by RockChinQ** [comment]
不太懂，可以让napcat那边看看
